### ISSUE TITLE
Graphs need to start at minimum m/z

### ISSUE THREAD

**Issue by tobigithub** [josharnoldjosh/massspectra#14]
Currently all the head-to-tail view graphs start at zero.
But many mass spectra have no m/z 1...20 or lower,
still the graphs offset for the x-range are wrong.

Solution: read in spectrum and determine smallest
m/z range. Use this value for scaling, also let some
space left and right maybe 5 m/z units.

This is for the online output as well as the directory output.
Tobias

**Comment by josharnoldjosh** [comment]
I believe this was fixed in the latest push I just did.

**Comment by tobigithub** [comment]
Tnx
