### ISSUE TITLE
Size of the static initial NN needs to go into settings

### ISSUE THREAD

**Issue by tobigithub** [josharnoldjosh/massspectra#19]
the definition of the input_dim_val , output_dim_val needs to go to
the definitions. For example larger datasets may be trained in the future.
````
class nn:
    def baseline_model(optimizer='Nadam', kernal_init='glorot_uniform', activation='relu', input_dim_val=1191, output_dim_val=800, l1_w=900, l2_w=800, l3_w=900, l1_d=0.2, l2_d=0.2):
        model = Sequential()

````

**Comment by josharnoldjosh** [comment]
Fixed in latest commit. Although input_dim_val is almost unnecessary because the code reads directly from the shape of the input to determine the input value.
