### ISSUE TITLE
Average similarity to main.py

### ISSUE THREAD

**Issue by tobigithub** [josharnoldjosh/massspectra#8]
Add average similarity to final text output in main.py to data.py

Example:
Test score: 1408.8923313
Average test accuracy: 0.659340663271
Average similarity : 0.958232849203
NN total train time: 0h:00m:32s

(also add headers to the similarity output text file
including Num, Similarity, Name)

**Comment by josharnoldjosh** [comment]
Already implemented:

Test score: 639.769523872
Average test accuracy: 0.659340663271
NN total train time: 0h:00m:28s
Average cosine similarity: 0.928380301441
