### ISSUE TITLE
Learning m/z range is too restricted vs actual molecular weight

### ISSUE THREAD

**Issue by tobigithub** [josharnoldjosh/massspectra#9]
There are some issues with the input files because
of restricted molecular weight ranges. For example
```
Name: Hexacontane
Formula: C60H122
MW: 842 Da
```
However our input file is restricted to MW400. Hence
the presented similarity in our case is correct, its
0.956, but the mass spectral similarity when searching the database
is actually low around 540 because the m/z range is actually much larger.
Basically all the indicative peaks >400 Da are missing, but they are crucial
for the identity of the spectrum.

See
webbook.nist.gov/cgi/inchi?ID=C7667803&Mask=200

Potential solution
1) export larger m/z ranges up to 800 Da in the input data file
2) exclude larger molecular wight compounds.

Lets discuss about that. This is an important issue, because we have almost 80 compounds > 400 Da.
The set is already small, excluding more is not good in terms of overfitting. The column x902 shows the molecular weight MW in the input CSV.
Tobias

**Comment by josharnoldjosh** [comment]
This is a little confusing, what should we do here? I am not sure I fully understand the problem.

**Comment by tobigithub** [comment]
Actually,
this is related to the input files generated by the descriptor software.
Some of the spectra have peaks > 400 Da, therefore the number
of columns (or m/z values) need to be increased accordingly.

For  the code it just means that the input ranges for x and y variables
can change. This is just a general comment.
